import type { EnvironmentMetadata } from "./types";

export const simulationEnvironmentCatalog: EnvironmentMetadata[] = [
  {
    id: "dynamic-attention",
    label: "Dynamic Attention Field",
    version: 1,
    validationStatus: "experimental",
    hypothesizedConstructs: ["attentionControl", "metacognitiveRegulation"],
    difficultyParameters: [
      "informationDensity",
      "distractorSimilarity",
      "interruptionLoad",
    ],
    traceTypes: [
      "signal-selection",
      "interruption",
      "decision",
      "confidence",
    ],
    knownConfounds: [
      "graph literacy",
      "visual acuity",
      "color vision",
      "motor speed",
      "device performance",
      "refresh rate",
      "touchscreen familiarity",
      "mouse/trackpad familiarity",
      "digital literacy",
    ],
    languageSensitivity: "low",
    deviceSensitivity: "high",
    accessibilityConsiderations: [
      "Provide step mode and textual signal values.",
      "Do not infer gaze or eye tracking from click behavior.",
      "Motion must respect reduced-motion preferences.",
    ],
    prototypeAvailable: true,
  },
  {
    id: "hidden-system-learning",
    label: "Hidden-System Learning",
    version: 1,
    validationStatus: "experimental",
    hypothesizedConstructs: ["modelFormation", "learningDynamics"],
    difficultyParameters: ["volatility", "ruleComplexity", "uncertainty"],
    traceTypes: [
      "rule-prediction",
      "rule-change-detection",
      "confidence",
      "revision",
    ],
    knownConfounds: [
      "numeracy",
      "working memory",
      "gaming familiarity",
      "motor speed",
    ],
    languageSensitivity: "low",
    deviceSensitivity: "low",
    accessibilityConsiderations: [
      "Avoid artificial timing pressure.",
      "Feedback must be available in text as well as visual state.",
    ],
    prototypeAvailable: true,
  },
  {
    id: "dynamic-evidence-stream",
    label: "Dynamic Evidence Stream",
    version: 1,
    validationStatus: "experimental",
    hypothesizedConstructs: [
      "epistemicJudgment",
      "metacognitiveRegulation",
      "modelFormation",
    ],
    difficultyParameters: [
      "uncertainty",
      "distractorSimilarity",
      "informationDensity",
    ],
    traceTypes: [
      "evidence-update",
      "decision",
      "confidence",
      "revision",
    ],
    knownConfounds: [
      "reading speed",
      "scientific literacy",
      "language proficiency",
    ],
    languageSensitivity: "high",
    deviceSensitivity: "medium",
    accessibilityConsiderations: [
      "Evidence must remain available in a readable history.",
      "Sequential updates require semantic announcements.",
    ],
    prototypeAvailable: true,
  },
  {
    id: "information-search",
    label: "Information Search Environment",
    version: 1,
    validationStatus: "hypothesized",
    hypothesizedConstructs: [
      "attentionControl",
      "epistemicJudgment",
      "metacognitiveRegulation",
    ],
    difficultyParameters: [
      "informationDensity",
      "uncertainty",
      "distractorSimilarity",
    ],
    traceTypes: [
      "information-request",
      "decision",
      "confidence",
    ],
    knownConfounds: [
      "digital literacy",
      "reading speed",
      "device type",
      "domain familiarity",
    ],
    languageSensitivity: "medium",
    deviceSensitivity: "high",
    accessibilityConsiderations: [
      "Information sources must be keyboard reachable.",
      "Inspection order must not depend on drag gestures.",
    ],
    prototypeAvailable: false,
  },
  {
    id: "structural-transfer",
    label: "Structural Transfer Environment",
    version: 1,
    validationStatus: "hypothesized",
    hypothesizedConstructs: ["knowledgeTransfer", "modelFormation"],
    difficultyParameters: [
      "transferDistance",
      "distractorSimilarity",
      "ruleComplexity",
    ],
    traceTypes: ["transfer-choice", "confidence", "decision"],
    knownConfounds: [
      "domain familiarity",
      "reading speed",
      "graph literacy",
      "working memory",
    ],
    languageSensitivity: "medium",
    deviceSensitivity: "medium",
    accessibilityConsiderations: [
      "Relational structures need equivalent textual descriptions.",
    ],
    prototypeAvailable: false,
  },
  {
    id: "adaptive-volatility",
    label: "Adaptive Rule / Volatility Environment",
    version: 1,
    validationStatus: "hypothesized",
    hypothesizedConstructs: ["learningDynamics", "modelFormation"],
    difficultyParameters: ["volatility", "uncertainty", "ruleComplexity"],
    traceTypes: [
      "rule-prediction",
      "rule-change-detection",
      "revision",
      "confidence",
    ],
    knownConfounds: [
      "working memory",
      "numeracy",
      "gaming familiarity",
    ],
    languageSensitivity: "low",
    deviceSensitivity: "low",
    accessibilityConsiderations: [
      "No reaction-time-only inference.",
      "Anomalies and rule changes require text-equivalent feedback.",
    ],
    prototypeAvailable: false,
  },
  {
    id: "ai-collaboration",
    label: "AI Collaboration Environment",
    version: 1,
    validationStatus: "hypothesized",
    hypothesizedConstructs: [
      "augmentedCognition",
      "epistemicJudgment",
      "metacognitiveRegulation",
    ],
    difficultyParameters: [
      "uncertainty",
      "distractorSimilarity",
      "informationDensity",
    ],
    traceTypes: [
      "ai-reliance",
      "information-request",
      "decision",
      "confidence",
    ],
    knownConfounds: [
      "AI familiarity",
      "digital literacy",
      "language proficiency",
      "domain familiarity",
    ],
    languageSensitivity: "high",
    deviceSensitivity: "medium",
    accessibilityConsiderations: [
      "AI advice must not be visually privileged over evidence.",
    ],
    prototypeAvailable: false,
  },
  {
    id: "uncertainty-decision",
    label: "Uncertainty & Decision Environment",
    version: 1,
    validationStatus: "hypothesized",
    hypothesizedConstructs: [
      "metacognitiveRegulation",
      "epistemicJudgment",
      "modelFormation",
    ],
    difficultyParameters: ["uncertainty", "informationDensity"],
    traceTypes: [
      "decision",
      "confidence",
      "information-request",
      "revision",
    ],
    knownConfounds: [
      "risk preference",
      "domain familiarity",
      "reading speed",
      "language proficiency",
    ],
    languageSensitivity: "medium",
    deviceSensitivity: "low",
    accessibilityConsiderations: [
      "Do not use time pressure as the only source of uncertainty.",
    ],
    prototypeAvailable: false,
  },
];
